haml:
  enabled: true

  linters:
    LineLength:
      Enabled: true
      Max: 140

ruby:
  enabled: true

  Rails:
    Enabled: true


LineLength:
  Description: 'Limit lines to 90 characters.'
  Enabled: true
  Max: 140
